### ISSUE TITLE
Hi! :wave: 

### ISSUE THREAD

**Issue by geropl** [Andorr/aoc-2020#1]
Hi  @Andorr :wave: ,

I'm writing you here because I could not find any contact details on your account.

I just stumbled over https://crates.io/crates/influxdb-client which I'm using in one of my projects. It seems to be the only influxdb 2.0 client crate that works out-of-the-box. The derive-macro is nice, too!

Would you mind making the repo open source (again) so others (including myself) could contribute?
If not that's also fine - just wanted to ask. 

Cheers!

**Comment by Andorr** [comment]
Hi, Gero

It is great that you found my crate useful. I decided to write my own influxdb-client when I was not able to find any other good rust-alternatives out there
for a project of mine, especially since InfluxDB moved to v2. Right now, it is still in its early stages and a lot is missing, so I gladly accept contributions. I have now
made the repo public, and will start making futher progress on it when I get time. Any feedback and contributions is very welcome!

The repo:
https://github.com/Andorr/influxdb-client-rs



Cheers!
Andorr
________________________________
Fra: Gero Posmyk-Leinemann ***@***.***>
Sendt: torsdag 11. mars 2021 21:11
Til: Andorr/aoc-2020 ***@***.***>
Kopi: Anders Hallem Iversen ***@***.***>; Mention ***@***.***>
Emne: [Andorr/aoc-2020] Hi! :wave: (#1)


Hi @Andorr<https://github.com/Andorr> 👋 ,

I'm writing you here because I could not find any contact details on your account.

I just stumbled over https://crates.io/crates/influxdb-client which I'm using in one of my projects. It seems to be the only influxdb 2.0 client crate that works out-of-the-box. The derive-macro is nice, too!

Would you mind making the repo open source (again) so others (including myself) could contribute?
If not that's also fine - just wanted to ask.

Cheers!

**Comment by geropl** [comment]
Thanks @Andorr , super nice! :pray:
